# Generated by Django 4.0.6 on 2022-08-22 05:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_orders_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='time',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
