# Generated by Django 4.0.6 on 2022-09-05 15:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_orders_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 5, 20, 49, 27, 487523)),
        ),
    ]
