# Generated by Django 4.0.6 on 2022-09-10 12:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_customer_last_login_alter_orders_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 10, 18, 11, 20, 663061)),
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('Order Placed', 'ORDER PLACED'), ('Shiped', 'SHIPED'), ('Out for delivery', 'OUT FOR DELIVERY'), ('Delivered', 'DELIVERED'), ('Failed', 'FAILED')], default='Order Placed', max_length=20),
        ),
    ]
