# Generated by Django 4.0.6 on 2022-09-10 13:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_customer_last_login_alter_orders_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipping_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('phone', models.BigIntegerField()),
                ('pincode', models.EmailField(max_length=254)),
                ('paymentmethod', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='customer',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 10, 18, 47, 42, 487071)),
        ),
    ]
