# Generated by Django 4.0.6 on 2022-09-10 14:04

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_shipping_details_alter_customer_last_login'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shipping_details',
        ),
        migrations.AddField(
            model_name='orders',
            name='name',
            field=models.CharField(default='cod', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orders',
            name='paymentdetails',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orders',
            name='pincode',
            field=models.IntegerField(default=123456),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 10, 19, 32, 12, 940487)),
        ),
    ]
