# Generated by Django 4.0.6 on 2022-09-14 04:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_orders_razorpay_order_id_alter_customer_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='razorpay_payment_id',
            field=models.CharField(default='payment1', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 14, 10, 6, 47, 704388)),
        ),
    ]
